language: node_js
node_js:
  - 10
  - 11
  - node

env:
  - IS_UNDER_TEST=true
  - IS_LOG_SILENT=true
  - IS_LOG_VERBOSE=false

install:
  - npm install

script:
  - npm clean:prepare:cover

after_success:
  - npm run coveralls

notifications:
  email: true

sudo: false